# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: didoudou
  timeout: 5000
  variables:
    sql_mode: TRADITIONAL

development:
  <<: *default
  database: ecommerce

test:
  <<: *default
  database: banque

production:
 url: <%= ENV['DATABASE_URL'] %>

